spring:
  zipkin:
    base-url: http://www.ticho.top:9411/
    sender:
      # activemq,rabbit,kafka,web
      type: web
  sleuth:
    sampler:
      # 抽样系数，默认0.1
      probability: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS